spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_URL}:${PROD_MYSQL_PORT}/projectx-database?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}